import "./globals.css"
import "./globals.scss"
import Lenis_Provider from "@/providers/Lenis_Provider"
import Experience_Provider from "@/providers/Experience_Provider"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body suppressHydrationWarning>
                <Lenis_Provider />
                <Experience_Provider>{children}</Experience_Provider>
            </body>
        </html>
    )
}
